//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTEDiploma.admin
{
    public partial class ExamCreation
    {
        /// <summary>
        /// ddlAcademicYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlAcademicYear;

        /// <summary>
        /// ddlYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;

        /// <summary>
        /// ddlMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMonth;

        /// <summary>
        /// txtStartDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;

        /// <summary>
        /// txtEndDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;

        /// <summary>
        /// txtRegularFee control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRegularFee;

        /// <summary>
        /// txtDueDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDueDate;

        /// <summary>
        /// gvExams control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvExams;

        /// <summary>
        /// btnSubmit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
